language: node_js
node_js:
  - 10
install:
  - yarn global add serverless@1.50
  - yarn install
script:
  - yarn lint
deploy:
  provider: script
  skip_cleanup: true
  script: NODE_ENV=production sls deploy -s production -v --force
  on:
    branch: master

