service:
  name: transformatter-json-services

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-2
  memorySize: 512

functions:
  v1:
    handler: src/handler.v1
    events:
      - http:
          method: any
          path: 'v1/{proxy+}'
custom:
  webpack:
    includeModules:
      forceInclude:
        - pg
